name: expo_fct_2020
description: App oficial da Expo FCT 2020

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bottom_navy_bar: ^5.3.2
  webview_flutter: ^0.3.19+7
  http: ^0.12.0+4
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+2
  google_maps_flutter: ^0.4.0
  font_awesome_flutter: ^8.2.0
  flutter_swiper: ^1.1.6
  expandable: ^4.1.2
  flutter_map: any # or the latest version on Pub
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/mapademo.PNG
    - assets/calendar.png
    - assets/home.png
    - assets/no_image.png
    - assets/house.png
    - assets/mountain.png
    - assets/plane.png
    - assets/world.png
    - assets/departamentos/
    - assets/edificios/

  fonts:
    - family: FlamanteRoma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf
          style: italic